version: "3.7"

services:
  sbt-server:
    container_name: sbt-server
    build:
      context: .
      dockerfile: ./docker/Dockerfile.app
    image: sbt-server
    ports:
      - "8080:8080"
  postgres-db:
    container_name: postgres-db
    build:
      context: ./docker/db/
      dockerfile: ./Dockerfile.db
    environment:
      POSTGRES_DB: typelevel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    image: postgres-db
    ports:
      - "5432:5432"
