version: "3.7"

services:
  postgres_db:
    build:
      context: ./docker/db/
      dockerfile: ./Dockerfile
    restart: always
    environment:
      POSTGRES_DB: ${DBNAME}
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./.docker-compose-data/postgres_data:/var/lib/postgresql/data
